# fly.toml app configuration file generated for moby-stt on 2025-08-01T17:50:56-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'moby-stt'
primary_region = 'iad'

[build]
  dockerfile = "./Dockerfile"

[[services]]
  internal_port = 3001
  protocol = "tcp"

  [[services.ports]]
    port = 3001

[[services]]
  internal_port = 3002
  protocol = "tcp"

  [[services.ports]]
    port = 3002

[[vm]]
  size = 'performance-1x'
