# fly.toml app configuration file generated for google-stt on 2025-08-02T15:08:16-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deepgram-stt'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 2
  
  [http_service.concurrency]
    type = "connections"
    soft_limit = 150
    hard_limit = 200

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    timeout = "5s"

[[vm]]
  size = "shared-cpu-2x"
  memory = "512mb"

[[restart]]
  policy = "on-failure"
  retries = 3